config/routes.rb
Rails.application.routes.draw do
  get 'renewals/new'
  get 'renewals/create'
  get 'reexams/new'

  devise_for :users

  authenticated :user do
    root to: "home#students", as: :authenticated_root
  end



  root to: "home#index"
  get 'application_status', to: 'home#application_status'
  get 'students/session_status', to: 'students#session_status', as: 'student_session_status'
  post 'admin/issue', to: 'admin#issue', as: 'admin_issue'
  get 'school_dashboard/pending', to: 'school_dashboard#pending', as: 'pending'
  get 'students/exam_status', to: 'students#exam_status', as: 'student_exam_status'
  get 'school_dashboard/approved', to: 'school_dashboard#approved'
  get 'school_dashboard/approve  authenticated :user do
    root to: "home#students", as: :authenticated_root
  endd', to: 'school_dashboard#approved', as: 'approved_students'
  post 'school_dashboard/mark', to: 'school_dashboard#mark', as: 'mark_students'
  get 'students/license_status', to: 'students#license_status', as: 'license_status'

  resources :school_dashboard do
    collection do
      get 'all_enrollees', to: 'school_dashboard#all_enrollees'
      get 'in_session', to: 'school_dashboard#in_session', as: 'in_session'
      post 'mark_exam_ready', to: 'school_dashboard#mark_exam_ready', as: 'mark_exam_ready'
      get 'test_scores'
    end
  end
  
  resources :students_applications, only: [:new, :create, :edit, :update] do
    get 'show', on: :member
    patch 'approve', on: :member
    patch 'reject', on: :member
  end

  namespace :admin do
    resources :schools, only: [:new, :create, :index, :show] do
      member do
        patch 'approve_reexam'
        patch 'reject_reexam'
      
      end
      collection do
        get 'list_students_with_session_started'
      end
    end

    resources :students, only: [] do
      resources :tests, only: [:create]
    end
  end
  get 'admin/renewal_applications', to: 'admin/schools#renewal_applications'
  get 'students/reexam', to: 'students#reexam_form', as: 'reexam_form'
  post 'students/submit_reexam', to: 'students#submit_reexam', as: 'submit_reexam'
  get 'schools_dashboard/approved', to: 'school_dashboard#approved', as: 'approved_enrolles' 
  

  resources :students, only: [:show, :edit, :update] do
    member do
      get 'profile'
    end
  end
  
  resources :admin, only: [:index] do
    collection do
      get :issue
      get 'reports', to: 'admin#reports'
    end
  end

  resources :renewals, only: [:new, :create]

end

app/views/admin/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Admin Page</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body class = "dashboards">

<!-- Sidebar -->
<div class="ezra-sidebar">
  <a href="http://127.0.0.1:3000/admin">
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
      <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4M3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707M2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10m9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5m.754-4.246a.39.39 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.39.39 0 0 0-.029-.518z"/>
      <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A8 8 0 0 1 0 10m8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3"/>
    </svg> Dashboard
  </a>
  <a href="http://127.0.0.1:3000/admin/schools/new">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" color="green" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
        </svg> Register New School
  </a>
  <a href="http://127.0.0.1:3000/admin/renewal_applications">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
        <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41m-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9"/>
        <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5 5 0 0 0 8 3M3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9z"/>
        </svg> Renewal Applications
  </a>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger logouts", form_class: "d-inline" %>
 
</div>


<!-- Page content -->
<div class="ezra-content">
  <nav class="nav-bar nav-3 dash-nav" style="background-color: #e9ecef;">
    <div>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Emblem_of_Ethiopia.svg/1200px-Emblem_of_Ethiopia.svg.png" alt="Federal Logo" 
              style="width: 70px; height: auto; border-radius: 50%; border: 1px solid #000; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);" />
    </div>
    <div class="nav-links">
         
         <a><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" color = "black" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
            </svg>
        </a>
    </div>
  </nav>

  <div class = "ezra-main-content">

      <h1>Welcome To Admin Page</h1>
      <div class = "dashboard-content">
          <div class="row">
           
                <div class="col-md-3">
                   <a href = "http://127.0.0.1:3000/admin/schools">
                  <div class = "box ezra-box p-2 mb-2 bg-light" style = "text-decoration: none; color: black">
                   <div class="icon-cont">
                      <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="white" fill="currentColor" class="bi bi-buildings-fill" viewBox="0 0 16 16">
                        <path d="M15 .5a.5.5 0 0 0-.724-.447l-8 4A.5.5 0 0 0 6 4.5v3.14L.342 9.526A.5.5 0 0 0 0 10v5.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V14h1v1.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5zM2 11h1v1H2zm2 0h1v1H4zm-1 2v1H2v-1zm1 0h1v1H4zm9-10v1h-1V3zM8 5h1v1H8zm1 2v1H8V7zM8 9h1v1H8zm2 0h1v1h-1zm-1 2v1H8v-1zm1 0h1v1h-1zm3-2v1h-1V9zm-1 2h1v1h-1zm-2-4h1v1h-1zm3 0v1h-1V7zm-2-2v1h-1V5zm1 0h1v1h-1z"/>
                      </svg>
                    </div>
                    Registered Schools
                  </div>
                    </a>
                </div>
        
    <div class="col-md-3">
      <div class="box ezra-box p-2 mb-2 bg-light">
        <div class = "icon-cont" style ="background-color: rgb(51, 51, 255);">
          <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="white"  fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
          </svg>
        </div>
        Approved Enrollments
      </div>
    </div>
    <div class="col-md-3">
      <%= link_to reports_admin_index_path do %>
        <div class="box p-2 ezra-box mb-2 bg-light">
          <div class="icon-cont" style="background-color: black;">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="white" fill="currentColor" class="bi bi-file-earmark-bar-graph-fill" viewBox="0 0 16 16">
                  <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1m.5 10v-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5m-2.5.5a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5zm-3 0a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5z"/>
                </svg>
          </div>
          Reports
        </div>
      <% end %>
    </div>

    <div class="col-md-3">
      <%= link_to issue_admin_index_path do %>
      <div class="box p-2 mb-2 bg-light ezra-box">
          <div class = "icon-cont" style ="background-color: rgb(226, 141, 29);">
          <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="black"  fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
          </svg>
        </div>
        Issue
      </div>
      <% end %>
    </div>
  </div>


</div>



<!-- jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



</body>
</html>

app/views/admin/issue.html.erb
<!-- View (ERB) -->
<h1 class="text-center my-4">Students List</h1>

<div class="table-responsive">
  <table class="table table-dark table-striped table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone Number</th>
        <th>Category</th>
        <th>School</th>
        <th>Session</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <% if student.session == 'completed' %> 
          <tr>
            <td><%= student.FirstName %></td>
            <td><%= student.LastName %></td>
            <td><%= student.phone_number %></td>
            <td><%= student.category %></td>
            <td><%= student.school.name %></td>
            <td><%= student.session %></td>
            <td>
              <%= form_tag admin_issue_path, method: :post do %>
                <%= hidden_field_tag :student_id, student.id %>
                <%= submit_tag "Issue", class: "btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/reports.html.erb
<!-- app/views/admin/reports.html.erb -->
<h1 class="my-4">Admin Reports</h1>

<div class="container">

  <h2 class="mt-5">Summary</h2>
  <ul class="list-group mb-5">
    <li class="list-group-item">Total Students: <%= @total_students %></li>
    <li class="list-group-item">Total Licenses Issued: <%= @total_licenses %></li>
    <li class="list-group-item">Total Schools: <%= @total_schools %></li>
  </ul>

  <h2 class="mt-5">Students per School</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>School Name</th>
        <th>Number of Students</th>
      </tr>
    </thead>
    <tbody>
      <% @students_per_school.each do |school| %>
        <tr>
          <td><%= school.name %></td>
          <td><%= school.student_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5">Students by Category</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Category</th>
        <th>Number of Students</th>
      </tr>
    </thead>
    <tbody>
      <% @students_by_category.each do |category, count| %>
        <tr>
          <td><%= category %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5">Licenses Expiring Soon</h2>
  <p>Number of licenses expiring within the next month: <%= @licenses_expiring_soon %></p>

  <h2 class="mt-5">Average Test Scores</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Student ID</th>
        <th>Student Name</th>
        <th>School Name</th>
        <th>Theory Exam</th>
        <th>Practical Exam</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @average_test_scores.each do |student| %>
        <tr>
          <td><%= student[:id] %></td>
          <td><%= "#{student[:FirstName]} #{student[:LastName]}" %></td>
          <td><%= student[:school_name] %></td>
          <td><%= student[:avg_theory_exam] %></td>
          <td><%= student[:avg_practical_exam] %></td>
          <td><%= student[:last_test_status] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5">Test Pass/Fail Rates</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Status</th>
        <th>Number of Tests</th>
      </tr>
    </thead>
    <tbody>
      <% @test_pass_fail_rates.each do |status, count| %>
        <tr>
          <td><%= status %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5">Reexamination Requests</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Status</th>
        <th>Number of Requests</th>
      </tr>
    </thead>
    <tbody>
      <% @reexam_requests.each do |status, count| %>
        <tr>
          <td><%= status %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5">Student Applications Status</h2>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Status</th>
        <th>Number of Applications</th>
      </tr>
    </thead>
    <tbody>
      <% @student_applications_status.each do |status, count| %>
        <tr>
          <td><%= status %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>