config/routes.rb
Rails.application.routes.draw do
  get 'renewals/new'
  get 'renewals/create'
  get 'reexams/new'

  devise_for :users

  authenticated :user do
    root to: "home#students", as: :authenticated_root
  end



  root to: "home#index"
  get 'application_status', to: 'home#application_status'
  get 'students/session_status', to: 'students#session_status', as: 'student_session_status'
  post 'admin/issue', to: 'admin#issue', as: 'admin_issue'
  get 'school_dashboard/pending', to: 'school_dashboard#pending', as: 'pending'
  get 'students/exam_status', to: 'students#exam_status', as: 'student_exam_status'
  get 'school_dashboard/approved', to: 'school_dashboard#approved'
  get 'school_dashboard/approve  authenticated :user do
    root to: "home#students", as: :authenticated_root
  endd', to: 'school_dashboard#approved', as: 'approved_students'
  post 'school_dashboard/mark', to: 'school_dashboard#mark', as: 'mark_students'
  get 'students/license_status', to: 'students#license_status', as: 'license_status'

  resources :school_dashboard do
    collection do
      get 'all_enrollees', to: 'school_dashboard#all_enrollees'
      get 'in_session', to: 'school_dashboard#in_session', as: 'in_session'
      post 'mark_exam_ready', to: 'school_dashboard#mark_exam_ready', as: 'mark_exam_ready'
      get 'test_scores'
    end
  end
  
  resources :students_applications, only: [:new, :create, :edit, :update] do
    get 'show', on: :member
    patch 'approve', on: :member
    patch 'reject', on: :member
  end

  namespace :admin do
    resources :schools, only: [:new, :create, :index, :show] do
      member do
        patch 'approve_reexam'
        patch 'reject_reexam'
      
      end
      collection do
        get 'list_students_with_session_started'
      end
    end

    resources :students, only: [] do
      resources :tests, only: [:create]
    end
  end
  get 'admin/renewal_applications', to: 'admin/schools#renewal_applications'
  get 'students/reexam', to: 'students#reexam_form', as: 'reexam_form'
  post 'students/submit_reexam', to: 'students#submit_reexam', as: 'submit_reexam'
  get 'schools_dashboard/approved', to: 'school_dashboard#approved', as: 'approved_enrolles' 
  

  resources :students, only: [:show, :edit, :update] do
    member do
      get 'profile'
    end
  end
  
  resources :admin, only: [:index] do
    collection do
      get :issue
      get 'reports', to: 'admin#reports'
    end
  end

  resources :renewals, only: [:new, :create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, only: [:students, :application_status]
  
    def index
    end
  
    def students
    end
  
    def application_status
      if current_user.present?
        @application_status = current_user.students_application&.status
        if @application_status.nil?
          flash[:alert] = "No application found for the current user."
        end
      else
        redirect_to login_path, alert: "Please log in to view your application status."
      end
    end
  end
  

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/application_status.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h1 class="display-4 mb-4">Application Status</h1>
            <% if @application_status.present? %>
                <p class="lead">Your application status: <strong><%= @application_status %></strong></p>
                <% if @application_status == 'rejected' %>
                    <%= link_to 'Reapply', edit_students_application_path(current_user.students_application), class: "btn btn-warning btn-lg mt-3" %>
                <% end %>
            <% else %>
                <p class="lead">No application submitted yet.</p>
            <% end %>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <%= stylesheet_link_tag 'home' %>
</head>
<body>
  <nav class="nav-bar"> 
    <div class = "geta">
      <div>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1200px-Flag_of_Ethiopia.svg.png" alt="Federal Logo" 
          style="width: 80px; height: auto; border: 1px solid #000; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);" />
        </div>
        <div>
          <h4 style = "color: white;">FDRE Ministry Of Transport</h4>
        </div>
    </div>
    <div class="nav-links">
      <%= link_to 'Sign in', new_user_session_path, class: "btn btn-secondary" %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary" %>
    </div>
  </nav>
  <nav class="nav-bar2">
    <div>
     <img src="https://github.com/Zel-hub7/bete/blob/main/src/logo-removebg.png?raw=true" alt="Federal Logo" 
          style="width: 150%; height: 70px;" />

    </div>
    <div class="nav-links2">
      <a href="https://www.motl.gov.et/service_category">About</a>
      <a href="https://www.motl.gov.et/contact">Contact</a>
    </div>
  </nav>

  <section class="main-section">
    <div class="Sub-Section">
      <h1 class="tag">DRIVING LICENSE REGISTRATION MANAGEMENT SYSTEM</h1>
      <%= link_to 'Enroll Now', new_user_registration_path, class: "enroll btn-success" %>

    </div>  
  
  </section>
  <footer class = "footer">
    <p>Copyright &copy; 2024 All rights reserved</p>
    <p>Developed by Ez T.</p>
  </footer>
</body>
</html>

app/views/home/students.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bootstrap Sidebar Example</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="dashboards">

<% if Student.exists?(user_id: current_user.id) %>
<% student = Student.find_by(user_id: current_user.id) %>
    <div class="ezra-sidebar">
    <a href="http://127.0.0.1:3000/students_applications/new">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
      </svg> Dashboard
    </a>
    <a href="/students/session_status">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" color="green" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg> Check Session Status
    </a>

    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger logouts", form_class: "d-inline" %>
  </div>

    <div class="ezra-content">
    <nav class="nav-bar dash-nav" style="background-color: #e6e6e6;">
      <div>
        <h6>Hi, <%= student.FirstName.capitalize %> </h6>
      </div>
      <div class="nav-links">
      <%= link_to profile_student_path(current_student) do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" color="black" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
        </svg>
      <% end %>

      </div>
    </nav>

<div class = "ezra-main-content">

    <h2><h1>You are enrolled in <%= student.school.name %></h2>

      <div class = "dashboard-content">
  <div class="row">
  <div class="col-md-3">
    <%= link_to student_exam_status_path, class: "box zola-box p-2 mb-2 bg-light", style: "text-decoration: none; color: black" do %>
      <div class="icon-cont">
      <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color = "white" fill="currentColor" class="bi bi-journal-text" viewBox="0 0 16 16">
        <path d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5"/>
        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2"/>
        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z"/>
      </svg>
      </div>
      Exam Status
    <% end %>
  </div>

<div class="col-md-3">
<a href="<%= license_status_path %>" class="text-decoration-none">
  <div class="box zola-box p-2 mb-2 bg-light">
    <div class="icon-cont" style="background-color: rgb(51, 51, 255);">
      <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="white" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
        <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
      </svg>
    </div>
    <span class="d-block">License Status</span>
  </div>
</a>

</div>

    <div class="col-md-3">
      <div class="box p-2 zola-box mb-2 bg-light">
        <div class = "icon-cont" style ="background-color: red;">
          <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="white"  fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
          </svg>
        </div>
        Cancelled
      </div>
    </div>
<div class="col-md-3">
  <a href="<%= in_session_school_dashboard_index_path %>" class="text-decoration-none">
    <div class="box p-2 mb-2 bg-light zola-box">
      <div class="icon-cont" style="background-color: rgb(226, 141, 29);">
        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" color="black" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
          <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
        </svg>
      </div>
      <span class="d-block">In-Session</span>
    </div>
  </a>
</div>

  </div>




  </div>
<% else %>
  <!-- Sidebar -->






  <%# Everything below this is for applicants which havent been enrolled as students %>
 

  <!-- Page content -->
  <section class = "sect5">
  <nav class="nav-bar"> 
    <div class = "geta">
      <div>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1200px-Flag_of_Ethiopia.svg.png" alt="Federal Logo" 
          style="width: 80px; height: auto; border: 1px solid #000; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);" />
        </div>
        <div>
          <h4 style = "color: white;">FDRE Ministry Of Transport</h4>
        </div>
    </div>
    <div class="nav-links">
    <a href="http://127.0.0.1:3000/application_status" class="btn btn-success">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        Check Application Status
    </a>

    </div>
  </nav>
  <nav class="nav-bar2">
    <div>
     <img src="https://github.com/Zel-hub7/bete/blob/main/src/logo-removebg.png?raw=true" alt="Federal Logo" 
          style="width: 150%; height: 70px;" />

    </div>
    <div class="nav-links2">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger logouts", form_class: "d-inline" %>
      
    </div>
  </nav>

  <section class="main-section">
    <div class="Sub-Section">
      <h1 class="tag">DRIVING LICENSE REGISTRATION MANAGEMENT SYSTEM</h1>
      <%= link_to 'Enroll Now', new_students_application_path, class: "enroll btn-success" %>

    </div>  
  
  </section>

  <footer class = "footer">
    <p>Copyright &copy; 2024 All rights reserved</p>
    <p>Developed by Ez T </p>
  </footer>


</section>
  

  
<% end %>

<!-- jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>